const actions = {
  ADD_POKEMON: 'ADD_POKEMON',
  ADD_DETAIL_POKEMON: 'ADD_DETAIL_POKEMON',
  ADD_NEXT_POKEMON: 'ADD_NEXT_POKEMON',
  ADD_PREV_POKEMON: 'ADD_PREV_POKEMON',
  ADD_TYPE: 'ADD_TYPE',
  
  //Loading
  LOADING: 'LOADING',
  DONE_LOADING: 'DONE_LOADING',

};

export default actions;
